apiVersion: apps/v1
kind: Deployment
metadata:
  name: giuhyu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: giuhyu
  template:
    metadata:
      labels:
        app: giuhyu
    spec:
      containers:
      - image: okteto.dev/giuhyu:latest
        name: giuhyu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "48e437e0-72bb-4fbc-894e-c6f4bbad56d8"
        - name: Vless_Path
          value: "/vl55bbs5"
        - name: Vmess_UUID
          value: "48e437e0-72bb-4fbc-894e-c6f4bbad56d8"
        - name: Vmess_Path
          value: "/vm66vvgy5567"
        - name: Share_Path
          value: "/v2link"
